const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const token = () => localStorage.getItem('dd_token');
const money = n => `ZMW ${Number(n || 0).toFixed(2)}`;
async function api(path, options={}) {
  const headers = {'Content-Type':'application/json', ...(options.headers||{})};
  if (token()) headers.Authorization = `Bearer ${token()}`;
  const response = await fetch(path, {...options, headers});
  if (response.status === 204) return null;
  const data = await response.json().catch(()=>({detail:'Unexpected server response'}));
  if (!response.ok) throw new Error(data.detail || 'Request failed');
  return data;
}
function notice(text, kind='info') { const box=$('#notice'); if(box){box.textContent=text;box.className=`notice ${kind}`;} }
function nav() { const el=$('#account-nav'); if(!el)return;const user=JSON.parse(localStorage.getItem('dd_user')||'{}');el.innerHTML=token()?`${user.is_seller?'<a href="/static/seller-dashboard.html">Seller studio</a>':''}${user.is_admin?'<a href="/static/admin-dashboard.html">Admin</a>':''}<button class="quiet" id="logout">Log out</button>`:'<a href="/">Sign in</a>'; $('#logout')?.addEventListener('click',()=>{localStorage.clear();location.href='/';}); }
const card = item => `<a class="item-card" href="/static/listing.html?id=${item.id}"><div class="item-image">${item.images?.[0]?.url?`<img src="${item.images[0].url}" alt="">`:'<span>DD</span>'}</div><div class="item-info"><span class="eyebrow">${item.category}</span><h3>${escapeHtml(item.title)}</h3><b>${money(item.price)}</b><small>${item.quantity} available</small></div></a>`;
function escapeHtml(value='') { return String(value).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
async function initAuth(){
  $('#login-form')?.addEventListener('submit', async e=>{e.preventDefault();try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});localStorage.setItem('dd_token',data.access_token);localStorage.setItem('dd_user',JSON.stringify(data.user));location.href='/static/marketplace.html';}catch(err){notice(err.message,'error');}});
  $('#signup-form')?.addEventListener('submit',async e=>{e.preventDefault();try{const data=await api('/auth/signup',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});$('#verify-token').value=data.verification_token;notice('Account created. Copy the development verification token below, then verify your email.','success');}catch(err){notice(err.message,'error');}});
  $('#verify-form')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/auth/verify',{method:'POST',body:JSON.stringify({token:$('#verify-token').value})});notice('Email verified. You can now sign in.','success');}catch(err){notice(err.message,'error');}});
}
async function initMarketplace(){
  const form=$('#filters'); async function load(){try{const q=new URLSearchParams([...new FormData(form)].filter(([,value])=>String(value).trim()!==''));const data=await api(`/listings?${q}`);$('#listing-grid').innerHTML=data.map(card).join('')||'<p class="empty">No approved listings match those filters.</p>';}catch(e){notice(e.message,'error');}}
  form?.addEventListener('submit',e=>{e.preventDefault();load();}); await load();
}
async function initListing(){
  const id=new URLSearchParams(location.search).get('id');if(!id)return notice('No listing selected','error');
  try{const item=await api(`/listings/${id}`);$('#detail').innerHTML=`<div class="detail-image">${item.images?.[0]?.url?`<img src="${item.images[0].url}" alt="${escapeHtml(item.title)}">`:'<span>DormDrop</span>'}</div><div><span class="eyebrow">${escapeHtml(item.category)}</span><h1>${escapeHtml(item.title)}</h1><p>${escapeHtml(item.description)}</p><h2>${money(item.price)}</h2><p>${item.length_cm} × ${item.width_cm} × ${item.height_cm} cm · ${item.weight_kg} kg</p><p>Seller: ${escapeHtml(item.seller.email)} · ${escapeHtml(item.seller.campus)} · ${escapeHtml(item.seller.dorm)} · ★ ${Number(item.seller.rating_avg).toFixed(1)}</p><label>Quantity <input id="quantity" type="number" min="1" max="${item.quantity}" value="1"></label><button id="add-cart">Add to cart</button><a class="quiet" href="/static/chat.html?peer=${item.seller.id}&listing=${item.id}">Message seller</a></div>`;const reviews=await api(`/sellers/${item.seller.id}/reviews`);$('#detail').insertAdjacentHTML('afterend',`<section class="panel section"><h2>Seller reviews</h2>${reviews.map(r=>`<p>★ ${r.rating} · ${escapeHtml(r.comment)} <small>— ${escapeHtml(r.buyer)}</small></p>`).join('')||'<p class="muted">No reviews yet.</p>'}</section>`);$('#add-cart').addEventListener('click',async()=>{try{await api('/cart/items',{method:'POST',body:JSON.stringify({listing_id:item.id,quantity:Number($('#quantity').value)})});notice('Added to your cart','success');}catch(e){notice(e.message,'error');}});}catch(e){notice(e.message,'error');}
}
async function initCart(){
  try{const data=await api('/cart');$('#cart-items').innerHTML=data.items.map(x=>`<article class="cart-row"><div><b>${escapeHtml(x.title)}</b><small>${money(x.price)} each</small></div><label>Qty <input data-qty="${x.id}" type="number" min="1" max="${x.available_quantity}" value="${x.quantity}"></label><b>${money(x.item_subtotal)}</b><small>Shipping ${money(x.item_shipping_fee)}</small><button class="quiet" data-remove="${x.id}">Remove</button></article>`).join('')||'<p class="empty">Your cart is empty.</p>';$('#subtotal').textContent=money(data.subtotal);$('#shipping').textContent=money(data.shipping_fee);$('#grand-total').textContent=money(data.grand_total);$$('[data-qty]').forEach(input=>input.onchange=async()=>{try{await api(`/cart/items/${input.dataset.qty}`,{method:'PUT',body:JSON.stringify({quantity:Number(input.value)})});initCart();}catch(e){notice(e.message,'error');}});$$('[data-remove]').forEach(btn=>btn.onclick=async()=>{await api(`/cart/items/${btn.dataset.remove}`,{method:'DELETE'});initCart();});}catch(e){notice(e.message,'error');}
}
async function initCheckout(){
  const cart=await api('/cart').catch(e=>{notice(e.message,'error');return null;});if(!cart)return;$('#checkout-summary').innerHTML=`<p>Items <b>${money(cart.subtotal)}</b></p><p>Shipping <b>${money(cart.shipping_fee)}</b></p><h2>Grand total <strong>${money(cart.grand_total)}</strong></h2>`;
  $('#checkout-form').addEventListener('submit',async e=>{e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));try{const order=await api('/checkout',{method:'POST',body:JSON.stringify(form)});notice(`Order ${order.order_id} placed · ${money(order.total)}`,'success');$('#checkout-form').hidden=true;$('#order-link').innerHTML=`<a class="button" href="/static/orders.html">Track order</a>`;}catch(err){notice(err.message,'error');}});
}
async function initOrders(){
  try{const orders=await api('/orders');$('#orders').innerHTML=orders.map(o=>{const sellers=[...new Map(o.items.filter(x=>x.seller_id).map(x=>[x.seller_id,x.seller_id])).values()];return `<article class="panel order-card"><div class="order-top"><div><span class="eyebrow">${o.order_id}</span><h2>${o.status.replaceAll('_',' ')}</h2></div><b>${money(o.total)}</b></div><div class="steps ${o.status}"><span class="${['picked_up','in_transit','delivered'].includes(o.status)?'done':''}">Picked Up</span><i></i><span class="${['in_transit','delivered'].includes(o.status)?'done':''}">In Transit</span><i></i><span class="${o.status==='delivered'?'done':''}">Delivered</span></div><p>Items ${money(o.subtotal)} · Shipping ${money(o.shipping_fee)}</p>${o.status==='delivered'?sellers.map(id=>`<form class="review-form" data-order="${o.order_id}" data-seller="${id}"><label>Rate seller #${id}<select name="rating"><option value="5">5 ★</option><option value="4">4 ★</option><option value="3">3 ★</option><option value="2">2 ★</option><option value="1">1 ★</option></select></label><input name="comment" placeholder="Write a review"><button>Submit review</button></form>`).join(''):''}</article>`;}).join('')||'<p class="empty">Your orders will appear here.</p>';$$('.review-form').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.order_id=form.dataset.order;data.seller_id=Number(form.dataset.seller);try{await api('/reviews',{method:'POST',body:JSON.stringify(data)});notice('Thank you for your review','success');form.remove();}catch(err){notice(err.message,'error');}});}catch(e){notice(e.message,'error');}
}
async function initSeller(){
  $('#seller-request-form')?.addEventListener('submit',async e=>{e.preventDefault();try{await api('/seller-requests',{method:'POST'});notice('Seller request submitted for admin review','success');}catch(err){notice(err.message,'error');}});
  try{const data=await api('/seller/dashboard');const admin=await api('/seller/admin-contact');$('#seller-request-panel').hidden=true;$('#seller-summary').innerHTML=`<div><b>${data.listings.length}</b><small>Listings</small></div><div><b>${money(data.gross_sales)}</b><small>Gross sales</small></div><div><b>${money(data.revenue_after_commission)}</b><small>After commission · ${money(data.paid_out)} paid out</small></div><div><a class="button" href="/static/chat.html?peer=${admin.id}">Chat with admin</a></div>`;$('#seller-listings').innerHTML=data.listings.map(x=>`<div class="table-row"><div><b>${escapeHtml(x.title)}</b><small>${x.status} · ${x.quantity} in stock</small></div><b>${money(x.price)}</b><button class="quiet" data-edit-listing="${x.id}">Edit</button>${x.status!=='sold'?`<button class="quiet" data-sold-listing="${x.id}">Mark sold</button>`:''}<button class="quiet" data-delete-listing="${x.id}">Delete</button></div>`).join('')||'<p>No listings yet.</p>';$('#seller-sales').innerHTML=data.sales.map(x=>{const next={awaiting_pickup:"picked_up",picked_up:"in_transit",in_transit:"delivered"}[x.status];return `<div class="table-row"><b>${x.order_id}</b><span>${x.status}</span><span>${x.quantity} sold</span><b>${money(x.gross)}</b>${next?`<button data-seller-advance="${x.order_id}" data-next-status="${next}">Mark ${next.replace("_"," ")}</button>`:""}</div>`;}).join('')||'<p>No sales yet.</p>';$$('[data-edit-listing]').forEach(b=>b.onclick=async()=>{const x=data.listings.find(v=>v.id===Number(b.dataset.editListing));const title=prompt('Listing title',x.title);if(title===null)return;const price=Number(prompt('Price in ZMW',x.price));if(!price)return;try{await api(`/listings/${x.id}`,{method:'PUT',body:JSON.stringify({...x,title,price,images:x.images})});notice('Changes submitted for approval','success');initSeller();}catch(e){notice(e.message,'error');}});$$('[data-sold-listing]').forEach(b=>b.onclick=async()=>{try{await api(`/listings/${b.dataset.soldListing}/sold`,{method:'POST'});notice('Listing marked sold','success');initSeller();}catch(e){notice(e.message,'error');}});$$('[data-delete-listing]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this listing?'))return;try{await api(`/listings/${b.dataset.deleteListing}`,{method:'DELETE'});notice('Listing deleted','success');initSeller();}catch(e){notice(e.message,'error');}});}catch(e){notice(e.message,'error');$('#seller-request-panel').hidden=false;$('#listing-form').closest('.panel').hidden=true;}
  $('#listing-form')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.price=Number(d.price);d.length_cm=Number(d.length_cm);d.width_cm=Number(d.width_cm);d.height_cm=Number(d.height_cm);d.weight_kg=Number(d.weight_kg);d.quantity=Number(d.quantity);d.images=d.image?[d.image]:[];delete d.image;try{await api('/listings',{method:'POST',body:JSON.stringify(d)});notice('Listing submitted for admin approval','success');e.currentTarget.reset();initSeller();}catch(err){notice(err.message,'error');}});
}
async function initAdmin(){
  const sections=[['/admin/listings/pending','pending-listings'],['/admin/listings','all-listings'],['/admin/seller-requests','seller-requests'],['/admin/users','admin-users'],['/admin/orders','admin-orders']];
  for(const [path,id] of sections){try{const data=await api(path);$('#'+id).dataset.payload=JSON.stringify(data);}catch(e){notice(e.message,'error');}}
  try{const c=await api('/admin/commissions');$('#commission-summary').innerHTML=`<h2>${money(c.total_earnings)}</h2><p>Total commission · ${(c.commission_rate*100).toFixed(1)}%</p>`;$('#commission-rows').innerHTML=c.entries.map(x=>`<div class="table-row"><b>${x.order_id}</b><span>Commission ${money(x.amount)}</span></div>`).join('')||'<p>No commissions yet.</p>';$('#payout-rows').innerHTML=c.payouts.map(x=>`<div class="table-row"><span>Seller #${x.seller_id} · ${escapeHtml(x.reference)}</span><b>${money(x.amount)}</b></div>`).join('')||'<p>No payouts recorded.</p>';}catch(e){notice(e.message,'error');}
  const pending=JSON.parse($('#pending-listings').dataset.payload||'[]');$('#pending-listings').innerHTML=pending.map(x=>`<article class="table-row"><div><b>${escapeHtml(x.title)}</b><small>${escapeHtml(x.category)} · ${money(x.price)}</small></div><button class="quiet" data-admin-edit="${x.id}">Edit title/price</button><button data-approve="${x.id}">Approve</button><button class="quiet" data-disapprove="${x.id}">Disapprove</button></article>`).join('')||'<p>No listings waiting for review.</p>';
  $$('[data-admin-edit]').forEach(b=>b.onclick=async()=>{const x=pending.find(v=>v.id===Number(b.dataset.adminEdit));const title=prompt('Listing title',x.title);if(title===null)return;const price=Number(prompt('Price in ZMW',x.price));if(!price)return;try{await api(`/admin/listings/${x.id}`,{method:'PUT',body:JSON.stringify({...x,title,price,images:x.images.map(i=>i.url)})});notice('Listing updated','success');initAdmin();}catch(e){notice(e.message,'error');}});
  $$('[data-approve]').forEach(b=>b.onclick=()=>adminAction(`/admin/listings/${b.dataset.approve}/approve`));$$('[data-disapprove]').forEach(b=>b.onclick=()=>adminAction(`/admin/listings/${b.dataset.disapprove}/disapprove`));
  const allListings=JSON.parse($('#all-listings').dataset.payload||'[]');$('#all-listings').innerHTML=allListings.map(x=>`<div class="table-row"><span>${escapeHtml(x.title)}</span><span>${x.status}</span><b>${money(x.price)}</b><button class="quiet" data-edit-any-listing="${x.id}">Edit</button></div>`).join('')||'<p>No listings exist.</p>';
  $$('[data-edit-any-listing]').forEach(b=>b.onclick=async()=>{const x=allListings.find(v=>v.id===Number(b.dataset.editAnyListing));const title=prompt('Listing title',x.title);if(title===null)return;const price=Number(prompt('Price in ZMW',x.price));if(!price)return;try{await api(`/admin/listings/${x.id}`,{method:'PUT',body:JSON.stringify({...x,title,price,images:x.images.map(i=>i.url)})});notice('Listing updated','success');initAdmin();}catch(e){notice(e.message,'error');}});
  const requests=JSON.parse($('#seller-requests').dataset.payload||'[]');$('#seller-requests').innerHTML=requests.map(x=>`<div class="table-row"><span>${escapeHtml(x.email)}</span><span>${x.status}</span>${x.status==='pending'?`<button data-seller-approve="${x.id}">Approve seller</button><button class="quiet" data-seller-reject="${x.id}">Reject</button>`:''}</div>`).join('')||'<p>No seller requests.</p>';
  $$('[data-seller-approve]').forEach(b=>b.onclick=()=>adminAction(`/admin/seller-requests/${b.dataset.sellerApprove}/approve`));$$('[data-seller-reject]').forEach(b=>b.onclick=()=>adminAction(`/admin/seller-requests/${b.dataset.sellerReject}/reject`));
  const users=JSON.parse($('#admin-users').dataset.payload||'[]');$('#admin-users').innerHTML=users.map(x=>`<div class="table-row"><span>#${x.id} · ${escapeHtml(x.email)}</span><span>${x.is_seller?'Seller':'Buyer'}</span><span>${x.is_suspended?'Suspended':'Active'}</span>${!x.is_admin?`<a href="/static/chat.html?peer=${x.id}">Message</a><button class="quiet" data-user-id="${x.id}" data-action="${x.is_suspended?'unsuspend':'suspend'}">${x.is_suspended?'Unsuspend':'Suspend'}</button>`:''}</div>`).join('')||'<p>No users found.</p>';
  $$('[data-user-id]').forEach(b=>b.onclick=()=>adminAction(`/admin/users/${b.dataset.userId}/${b.dataset.action}`));
  $('#payout-form')?.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.seller_id=Number(d.seller_id);d.amount=Number(d.amount);try{await api('/admin/payouts',{method:'POST',body:JSON.stringify(d)});notice('Seller payout recorded','success');initAdmin();}catch(err){notice(err.message,'error');}});
  const orders=JSON.parse($('#admin-orders').dataset.payload||'[]');$('#admin-orders').innerHTML=orders.map(x=>{const next={awaiting_pickup:'picked_up',picked_up:'in_transit',in_transit:'delivered'}[x.status];return `<div class="table-row"><b>${x.order_id}</b><span>${x.status}</span><b>${money(x.total)}</b>${next?`<button data-advance-order="${x.order_id}" data-next-status="${next}">Mark ${next.replace('_',' ')}</button>`:''}</div>`;}).join('')||'<p>No orders yet.</p>';
  $$('[data-advance-order]').forEach(b=>b.onclick=async()=>{try{await api(`/admin/orders/${b.dataset.advanceOrder}/status`,{method:'PUT',body:JSON.stringify({status:b.dataset.nextStatus})});notice('Order status updated','success');initAdmin();}catch(e){notice(e.message,'error');}});
}
async function adminAction(path){try{await api(path,{method:'POST'});notice('Updated successfully','success');initAdmin();}catch(e){notice(e.message,'error');}}
async function initChat(){
  const params=new URLSearchParams(location.search);$('#peer').value=params.get('peer')||'';$('#listing-context').value=params.get('listing')||'';$('#order-context').value=params.get('order')||'';
  async function load(){const peer=$('#peer').value;if(!peer)return;try{const messages=await api(`/messages/${peer}`);$('#chat-log').innerHTML=messages.map(x=>`<div class="bubble ${x.sender_id===Number(JSON.parse(localStorage.getItem('dd_user')||'{}').id)?'mine':''}">${escapeHtml(x.body)}<small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('');$('#chat-log').scrollTop=$('#chat-log').scrollHeight;}catch(e){notice(e.message,'error');}}
  $('#load-chat').onclick=load;$('#chat-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.receiver_id=Number($('#peer').value);d.listing_id=d.listing_id?Number(d.listing_id):null;d.order_id=d.order_id||null;try{await api('/messages',{method:'POST',body:JSON.stringify(d)});$('#message-body').value='';load();}catch(err){notice(err.message,'error');}};if($('#peer').value)load();
}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-seller-advance]');if(!button)return;try{await api(`/admin/orders/${button.dataset.sellerAdvance}/status`,{method:'PUT',body:JSON.stringify({status:button.dataset.nextStatus})});notice('Order status updated','success');initSeller();}catch(e){notice(e.message,'error');}});
document.addEventListener('DOMContentLoaded',()=>{nav();const page=document.body.dataset.page;const init={auth:initAuth,marketplace:initMarketplace,listing:initListing,cart:initCart,checkout:initCheckout,orders:initOrders,seller:initSeller,admin:initAdmin,chat:initChat}[page];if(init)init().catch(e=>notice(e.message,'error'));});
